name: Create or Update Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name (e.g., v1.0.0)
        required: true
        default: v1.0.0
      target:
        description: Target commitish (branch or SHA)
        required: false
        default: main
      prerelease:
        description: Mark as prerelease
        type: boolean
        required: false
        default: false
      draft:
        description: Create as draft
        type: boolean
        required: false
        default: false
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create or update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref_name || inputs.tag }}
          commitish: ${{ github.event_name == 'push' && github.sha || inputs.target }}
          name: PolliLib ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref_name || inputs.tag }}
          body: |
            # PolliLib ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref_name || inputs.tag }}
            Stable cross-language release: Python + JavaScript clients, shared AST.
            Highlights: images (flux, 512x512, nologo, 5-8 digit seed), text, chat (SSE + tools), vision, stt, public feeds, referrer/token, AST in /AST.
            Tests: pytest python/tests; node --test javascript/tests
          draft: ${{ github.event_name == 'workflow_dispatch' && inputs.draft || false }}
          prerelease: ${{ github.event_name == 'workflow_dispatch' && inputs.prerelease || false }}
          allowUpdates: true
          makeLatest: true
          omitNameDuringUpdate: false
          omitBodyDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}

